spring.application.name=ttracker
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/ttracker?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:nandani}
spring.datasource.password=${DB_PASS:212002}

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false


logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

security.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_32+_CHARS
security.jwt.expiration-seconds=3600

spring.data.redis.password=212002
